import {getChatGPTUser} from '../../chatgpt-auth';
import {database,bucket} from '../../../lib/database';
import {apply,validateProject} from '../../../public/studio/model.js';
export const dynamic='force-dynamic';
const fail=(message:string,status=400)=>{throw Object.assign(new Error(message),{status})};
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
async function handle(req:Request){try{const url=new URL(req.url),path=url.pathname.slice(5).split('/').filter(Boolean),method=req.method;
if(!['GET','HEAD'].includes(method)){const origin=req.headers.get('origin');if(origin&&origin!==url.origin)fail('Request origin is not allowed',403);if(Number(req.headers.get('content-length')||0)>30*1024*1024)fail('File is too large',413)}
const user=await getChatGPTUser();if(!user)fail('Sign in to save and share your designs',401);const db=database(),email=user.email.toLowerCase();
const body=async()=>{const t=await req.text();if(t.length>3_000_000)fail('Design is too large',413);try{return JSON.parse(t)}catch{fail('Invalid request')}};
async function access(id:string,level='view'){const p:any=await db.prepare('SELECT * FROM projects WHERE id = ? AND deleted = 0').bind(id).first();if(!p)fail('Design not found',404);let role=p.owner===user!.userId?'owner':null;if(!role){const m:any=await db.prepare('SELECT role FROM members WHERE project = ? AND email = ?').bind(id,email).first();role=m?.role}const token=req.headers.get('X-Velora-Share')||url.searchParams.get('share');if(role!=='owner'&&token){const link:any=await db.prepare('SELECT role FROM links WHERE token = ? AND project = ?').bind(await hash(token),id).first();const rank:any={view:1,comment:2,edit:3};if(link&&(!role||rank[link.role]>rank[role]))role=link.role}if(!role)fail('You do not have access to this design',403);if(level==='edit'&&!['owner','edit'].includes(role))fail('This design is read only',403);if(level==='comment'&&!['owner','edit','comment'].includes(role))fail('Comment access is required',403);if(level==='owner'&&role!=='owner')fail('Only the owner can change sharing',403);return {...p,role}}
async function copyAssets(data:any){const mapped=new Map<string,string>();for(const pg of data.pages)for(const o of pg.objects){if(!o.src?.startsWith('/api/assets/'))continue;const old=o.src.slice('/api/assets/'.length);if(mapped.has(old)){o.src=mapped.get(old);continue}const a:any=await db.prepare('SELECT * FROM assets WHERE id=?').bind(old).first();if(!a)fail('A media file in this design is missing');await access(a.project);const source=await bucket().get(old);if(!source)fail('A media file in this design is unavailable');const aid=crypto.randomUUID();await bucket().put(aid,source.body,{httpMetadata:{contentType:a.mime}});await db.prepare('INSERT INTO assets (id,project,owner,name,mime,size,created) VALUES (?,?,?,?,?,?,?)').bind(aid,data.id,user!.userId,a.name,a.mime,a.size,Date.now()).run();const src='/api/assets/'+aid;mapped.set(old,src);o.src=src}}
if(path[0]==='me')return json({id:user.userId,name:user.fullName||user.email.split('@')[0],email:user.email});
if(path[0]==='projects'&&path.length===1){if(method==='GET'){const r=await db.prepare('SELECT DISTINCT p.id,p.name,p.updated,p.folder,p.starred,p.owner,p.revision,p.data FROM projects p LEFT JOIN members m ON m.project=p.id WHERE p.deleted=0 AND (p.owner=? OR m.email=?) ORDER BY p.updated DESC LIMIT 150').bind(user.userId,email).all();return json(r.results.map((p:any)=>{const d=JSON.parse(p.data);return {...p,data:undefined,preview:d.pages[0],width:d.width,height:d.height,pageCount:d.pages.length}}))}if(method==='POST'){const data=validateProject(await body());data.id=crypto.randomUUID();await copyAssets(data);await db.prepare('INSERT INTO projects (id,owner,name,data,updated) VALUES (?,?,?,?,?)').bind(data.id,user.userId,data.name,JSON.stringify(data),Date.now()).run();return json({data,revision:0,role:'owner'},201)}}
if(path[0]==='projects'&&path[1]){const id=path[1],sub=path[2];if(!sub){if(method==='GET'){const p=await access(id);return json({data:JSON.parse(p.data),revision:p.revision,role:p.role})}if(method==='DELETE'){await access(id,'owner');await db.prepare('UPDATE projects SET deleted=1 WHERE id=?').bind(id).run();return json({ok:true})}if(method==='PATCH'){await access(id,'owner');const b=await body();await db.prepare('UPDATE projects SET folder=?,starred=? WHERE id=?').bind(String(b.folder||'').slice(0,80),b.starred?1:0,id).run();return json({ok:true})}}
if(sub==='sync'){if(method==='GET'){const p=await access(id);const since=Number(url.searchParams.get('since')||0);const people=await db.prepare('SELECT actor,name,page,x,y FROM presence WHERE project=? AND updated>?').bind(id,Date.now()-20000).all();return json({revision:p.revision,data:p.revision>since?JSON.parse(p.data):null,presence:people.results,role:p.role})}if(method==='POST'){await access(id,'edit');const b=await body();if(typeof b.id!=='string'||b.id.length>100||!Array.isArray(b.changes)||b.changes.length>5000)fail('Invalid change batch');const old:any=await db.prepare('SELECT revision,project FROM operations WHERE id=?').bind(b.id).first();if(old){if(old.project!==id)fail('Invalid operation identifier');const p=await access(id);return json({revision:p.revision,data:JSON.parse(p.data)})}for(let i=0;i<5;i++){const p=await access(id,'edit');const data=validateProject(apply(JSON.parse(p.data),b.changes));if(JSON.stringify(data).length>2_000_000)fail('Design is too large');const rev=p.revision+1;const results=await db.batch([db.prepare('UPDATE projects SET data=?,name=?,revision=?,updated=?,last_op=? WHERE id=? AND revision=? AND NOT EXISTS(SELECT 1 FROM operations WHERE id=?)').bind(JSON.stringify(data),data.name,rev,Date.now(),b.id,id,p.revision,b.id),db.prepare('INSERT INTO operations (id,project,actor,revision,changes,created) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM projects WHERE id=? AND last_op=?) AND NOT EXISTS(SELECT 1 FROM operations WHERE id=?)').bind(b.id,id,user.userId,rev,JSON.stringify(b.changes),Date.now(),id,b.id,b.id)]);if(results[0].meta.changes)return json({revision:rev,data});const duplicate:any=await db.prepare('SELECT revision FROM operations WHERE id=? AND project=?').bind(b.id,id).first();if(duplicate){const current=await access(id);return json({revision:current.revision,data:JSON.parse(current.data)})}}fail('The design is busy. Changes will retry.',409)}}
if(sub==='presence'&&method==='POST'){await access(id);const b=await body();await db.prepare('INSERT INTO presence (project,actor,name,page,x,y,updated) VALUES (?,?,?,?,?,?,?) ON CONFLICT(project,actor) DO UPDATE SET name=excluded.name,page=excluded.page,x=excluded.x,y=excluded.y,updated=excluded.updated').bind(id,user.userId,user.fullName||email.split('@')[0],String(b.page||''),Math.round(Number(b.x)||0),Math.round(Number(b.y)||0),Date.now()).run();return json({ok:true})}
if(sub==='comments'){await access(id,method==='GET'?'view':'comment');if(method==='GET')return json((await db.prepare('SELECT * FROM comments WHERE project=? ORDER BY created').bind(id).all()).results);const b=await body();if(method==='POST'){const text=String(b.body||'').trim();if(!text||text.length>5000)fail('Write a comment of up to 5,000 characters');await db.prepare('INSERT INTO comments (id,project,page,author,name,body,created) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,String(b.page),user.userId,user.fullName||email.split('@')[0],text,Date.now()).run()}if(method==='PATCH')await db.prepare('UPDATE comments SET resolved=? WHERE id=? AND project=?').bind(b.resolved?1:0,b.id,id).run();return json({ok:true})}
if(sub==='sharing'){await access(id,'owner');if(method==='GET')return json({members:(await db.prepare('SELECT email,role FROM members WHERE project=?').bind(id).all()).results,links:(await db.prepare('SELECT role,created FROM links WHERE project=?').bind(id).all()).results});const b=await body();if(method==='DELETE'){if(!b.email)await db.prepare('DELETE FROM links WHERE project=?').bind(id).run();if(b.email)await db.prepare('DELETE FROM members WHERE project=? AND email=?').bind(id,String(b.email).toLowerCase()).run();return json({ok:true})}if(!['view','comment','edit'].includes(b.role))fail('Invalid permission');if(b.email){const em=String(b.email).trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em))fail('Enter a valid email');await db.prepare('INSERT INTO members (project,email,role) VALUES (?,?,?) ON CONFLICT(project,email) DO UPDATE SET role=excluded.role').bind(id,em,b.role).run();return json({ok:true})}const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare('INSERT INTO links (token,project,role,created) VALUES (?,?,?,?)').bind(await hash(token),id,b.role,Date.now()).run();return json({token})}
if(sub==='snapshots'){await access(id,method==='GET'?'view':'edit');if(method==='GET'){if(path[3]){const snap:any=await db.prepare('SELECT data FROM snapshots WHERE id=? AND project=?').bind(path[3],id).first();if(!snap)fail('Version not found',404);return json(JSON.parse(snap.data))}return json((await db.prepare('SELECT id,name,created FROM snapshots WHERE project=? ORDER BY created DESC LIMIT 50').bind(id).all()).results)}const p=await access(id,'edit'),b=await body();await db.prepare('INSERT INTO snapshots (id,project,name,data,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,String(b.name||'Saved version').slice(0,100),p.data,Date.now()).run();return json({ok:true})}
if(sub==='assets'){await access(id,method==='GET'?'view':'edit');if(method==='GET')return json((await db.prepare('SELECT id,name,mime,size FROM assets WHERE project=? ORDER BY created DESC').bind(id).all()).results);if(method==='POST'){const form=await req.formData(),file=form.get('file');if(!(file instanceof File))fail('Select a file');if(file.size>25*1024*1024)fail('Maximum file size is 25 MB');if(!['image/png','image/jpeg','image/webp','image/gif','video/mp4','video/webm','audio/mpeg','audio/wav'].includes(file.type))fail('Use PNG, JPG, WebP, GIF, MP4, WebM, MP3 or WAV');const aid=crypto.randomUUID();await bucket().put(aid,file.stream(),{httpMetadata:{contentType:file.type}});await db.prepare('INSERT INTO assets (id,project,owner,name,mime,size,created) VALUES (?,?,?,?,?,?,?)').bind(aid,id,user.userId,file.name.slice(0,160),file.type,file.size,Date.now()).run();return json({id:aid,name:file.name,mime:file.type,size:file.size,src:'/api/assets/'+aid},201)}}}
if(path[0]==='assets'&&path[1]&&method==='GET'){const asset:any=await db.prepare('SELECT * FROM assets WHERE id=?').bind(path[1]).first();if(!asset)fail('Media not found',404);await access(asset.project);const obj=await bucket().get(asset.id);if(!obj)fail('Media not found',404);return new Response(obj.body,{headers:{'Content-Type':asset.mime,'Cache-Control':'private,max-age=300','X-Content-Type-Options':'nosniff'}})}
return json({error:'Not found'},404)
}catch(e:any){if(!e.status)console.error('Velora API:',e);return json({error:e.status?e.message:'We could not complete this request. Your changes are still in the editor.'},e.status||500)}}
export const GET=handle;export const POST=handle;export const PATCH=handle;export const DELETE=handle;
