import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {DatabaseSync} from 'node:sqlite';import {apply,validateProject,starter,clone,diff} from '../public/studio/model.js';
let actor={userId:'owner',email:'owner@example.org',fullName:'Owner'};let activeDb;const blobs=new Map();
class Prepared{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new Prepared(this.sql,args)}async first(){return activeDb.prepare(this.sql).get(...this.args)||null}async all(){return{results:activeDb.prepare(this.sql).all(...this.args)}}async run(){const r=activeDb.prepare(this.sql).run(...this.args);return{meta:{changes:Number(r.changes)}}}}
const db={prepare:s=>new Prepared(s),batch:async statements=>{activeDb.exec('BEGIN');try{const result=[];for(const s of statements){const r=activeDb.prepare(s.sql).run(...s.args);result.push({meta:{changes:Number(r.changes)}})}activeDb.exec('COMMIT');return result}catch(e){activeDb.exec('ROLLBACK');throw e}}};
const bucket=()=>({put:async(id,body,meta)=>{blobs.set(id,{body:new Uint8Array(await new Response(body).arrayBuffer()),...meta})},get:async id=>{const a=blobs.get(id);return a?{...a,body:a.body.slice()}:null}});
let source=fs.readFileSync(new URL('../app/api/[...path]/route.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'');source=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;const context=vm.createContext({getChatGPTUser:async()=>actor,database:()=>db,bucket,apply,validateProject,Response,Request,File,URL,crypto,TextEncoder,console,setTimeout,Date});vm.runInContext(source+'\nglobalThis.api=handle;',context);
async function call(path,method='GET',body,headers={}){const req=new Request('https://velora.test/api/'+path,{method,headers:body?{'Content-Type':'application/json',...headers}:headers,...(body?{body:JSON.stringify(body)}:{})});const r=await context.api(req);return{status:r.status,body:await r.json()}}
function reset(){activeDb?.close();activeDb=new DatabaseSync(':memory:');activeDb.exec(fs.readFileSync(new URL('../drizzle/0000_silky_zemo.sql',import.meta.url),'utf8').replaceAll('--> statement-breakpoint',''));actor={userId:'owner',email:'owner@example.org',fullName:'Owner'};blobs.clear()}
async function create(){const r=await call('projects','POST',starter());assert.equal(r.status,201,JSON.stringify(r.body));return r.body}
test('API creates and durably reloads a design',async()=>{reset();const r=await create();const reload=await call('projects/'+r.data.id);assert.deepEqual(reload.body.data,r.data);assert.equal((await call('projects')).body.length,1)});
test('server rejects unauthenticated access and cross-origin writes',async()=>{reset();actor=null;assert.equal((await call('me')).status,401);actor={userId:'owner',email:'owner@example.org'};assert.equal((await call('projects','POST',starter(),{Origin:'https://evil.test'})).status,403)});
test('server denies another account read and write',async()=>{reset();const r=await create();actor={userId:'stranger',email:'other@example.org'};assert.equal((await call('projects/'+r.data.id)).status,403);assert.equal((await call(`projects/${r.data.id}/sync`,'POST',{id:crypto.randomUUID(),changes:[]})).status,403)});
test('operation retry is deduplicated and revision advances once',async()=>{reset();const r=await create(),id=r.data.id;const op={id:crypto.randomUUID(),changes:[{kind:'project',key:'name',value:'Edited'}]};const a=await call(`projects/${id}/sync`,'POST',op),b=await call(`projects/${id}/sync`,'POST',op);assert.equal(a.status,200);assert.equal(b.body.revision,1);assert.equal(b.body.data.name,'Edited');assert.equal(activeDb.prepare('SELECT COUNT(*) AS n FROM operations').get().n,1)});
test('concurrent operation batches retain independent property changes',async()=>{reset();const r=await create(),id=r.data.id;const op=v=>({id:crypto.randomUUID(),changes:[{kind:'project',...v}]});await Promise.all([call(`projects/${id}/sync`,'POST',op({key:'name',value:'Together'})),call(`projects/${id}/sync`,'POST',op({key:'width',value:1400}))]);const p=await call('projects/'+id);assert.equal(p.body.data.name,'Together');assert.equal(p.body.data.width,1400);assert.equal(p.body.revision,2)});
test('view and comment grants enforce write restrictions',async()=>{reset();const r=await create(),id=r.data.id;await call(`projects/${id}/sharing`,'POST',{email:'viewer@example.org',role:'view'});actor={userId:'viewer',email:'viewer@example.org'};assert.equal((await call('projects/'+id)).status,200);assert.equal((await call(`projects/${id}/sync`,'POST',{id:crypto.randomUUID(),changes:[]})).status,403);assert.equal((await call(`projects/${id}/comments`,'POST',{page:r.data.pages[0].id,body:'Hello'})).status,403)});
test('edit link grants access and explicit revocation removes it',async()=>{reset();const r=await create(),id=r.data.id;const link=await call(`projects/${id}/sharing`,'POST',{role:'edit'});actor={userId:'link-user',email:'link@example.org'};const h={'X-Velora-Share':link.body.token};assert.equal((await call('projects/'+id,'GET',null,h)).body.role,'edit');actor={userId:'owner',email:'owner@example.org'};await call(`projects/${id}/sharing`,'DELETE',{});actor={userId:'link-user',email:'link@example.org'};assert.equal((await call('projects/'+id,'GET',null,h)).status,403)});
test('removing a member does not revoke unrelated share links',async()=>{reset();const r=await create(),id=r.data.id;await call(`projects/${id}/sharing`,'POST',{email:'member@example.org',role:'edit'});await call(`projects/${id}/sharing`,'POST',{role:'view'});await call(`projects/${id}/sharing`,'DELETE',{email:'member@example.org'});assert.equal(activeDb.prepare('SELECT COUNT(*) n FROM links').get().n,1);assert.equal(activeDb.prepare('SELECT COUNT(*) n FROM members').get().n,0)});
test('comment text is persisted and can be resolved',async()=>{reset();const r=await create(),id=r.data.id;assert.equal((await call(`projects/${id}/comments`,'POST',{page:r.data.pages[0].id,body:'Consider a larger heading.'})).status,200);const c=(await call(`projects/${id}/comments`)).body[0];await call(`projects/${id}/comments`,'PATCH',{id:c.id,resolved:true});assert.equal((await call(`projects/${id}/comments`)).body[0].resolved,1)});
test('snapshot preserves old state after subsequent edits',async()=>{reset();const r=await create(),id=r.data.id;await call(`projects/${id}/snapshots`,'POST',{name:'Before edit'});await call(`projects/${id}/sync`,'POST',{id:crypto.randomUUID(),changes:[{kind:'project',key:'name',value:'After'}]});const v=(await call(`projects/${id}/snapshots`)).body[0];assert.equal((await call(`projects/${id}/snapshots/${v.id}`)).body.name,r.data.name)});
test('malformed rendering properties return 400 without changing revision',async()=>{reset();const r=await create(),id=r.data.id;const bad={id:crypto.randomUUID(),changes:[{kind:'object',page:r.data.pages[0].id,id:r.data.pages[0].objects[0].id,props:{radius:'0" onload="alert(1)'}}]};assert.equal((await call(`projects/${id}/sync`,'POST',bad)).status,400);assert.equal((await call('projects/'+id)).body.revision,0)});
test('duplicate project copies stored media to independent ownership',async()=>{reset();const r=await create(),id=r.data.id,aid=crypto.randomUUID();blobs.set(aid,{body:new Uint8Array([1,2,3]),httpMetadata:{contentType:'image/png'}});activeDb.prepare('INSERT INTO assets (id,project,owner,name,mime,size,created) VALUES (?,?,?,?,?,?,?)').run(aid,id,'owner','test.png','image/png',3,Date.now());r.data.pages[0].objects[0].src='/api/assets/'+aid;const duplicate=await call('projects','POST',r.data);assert.equal(duplicate.status,201);const copied=duplicate.body.data.pages[0].objects[0].src.split('/').pop();assert.notEqual(copied,aid);assert.equal(activeDb.prepare('SELECT project FROM assets WHERE id=?').get(copied).project,duplicate.body.data.id)});
