import test from 'node:test';import assert from 'node:assert/strict';import {LocalAPI} from '../public/studio/local-store.js';import {starter,clone} from '../public/studio/model.js';
globalThis.BroadcastChannel=undefined;
class Store{constructor(){this.tables=new Map()}table(n){if(!this.tables.has(n))this.tables.set(n,new Map());return this.tables.get(n)}async get(n,id){return structuredClone(this.table(n).get(id))}async all(n){return structuredClone([...this.table(n).values()])}async put(n,v){this.table(n).set(v.id,structuredClone(v));return v}async putMany(records){for(const r of records)await this.put(r.store,r.value)}async patchProject(id,props){const p=await this.get('projects',id);Object.assign(p,props);await this.put('projects',p);return p}}
const setup=()=>new LocalAPI(new Store());const create=async api=>(await api.request('projects',{method:'POST',body:JSON.stringify(starter())})).data;const req=(api,path,method,body)=>api.request(path,{method,body:JSON.stringify(body)});
test('Pages creates and reloads a project through the local adapter',async()=>{const api=setup(),p=await create(api),r=await api.request('projects/'+p.id);assert.deepEqual(r.data,p);assert.equal((await api.request('projects')).length,1);assert.equal(r.role,'owner')});
test('Pages folders stars and trash are stored',async()=>{const api=setup(),p=await create(api);await req(api,'projects/'+p.id,'PATCH',{folder:'Campaign',starred:true});const list=await api.request('projects');assert.equal(list[0].folder,'Campaign');assert.equal(list[0].starred,1);await req(api,'projects/'+p.id,'DELETE',{});assert.equal((await api.request('projects')).length,0);await assert.rejects(()=>api.request('projects/'+p.id),/not saved on this device/)});
test('Pages snapshots preserve an editable design',async()=>{const api=setup(),p=await create(api);await req(api,`projects/${p.id}/snapshots`,'POST',{name:'Checkpoint'});const s=(await api.request(`projects/${p.id}/snapshots`))[0];assert.equal(s.name,'Checkpoint');assert.deepEqual(await api.request(`projects/${p.id}/snapshots/${s.id}`),p)});
test('Pages personal notes persist and resolve',async()=>{const api=setup(),p=await create(api);await req(api,`projects/${p.id}/comments`,'POST',{page:p.pages[0].id,body:'Move heading'});const c=(await api.request(`projects/${p.id}/comments`))[0];await req(api,`projects/${p.id}/comments`,'PATCH',{id:c.id,resolved:true});assert.equal((await api.request(`projects/${p.id}/comments`))[0].resolved,1)});
test('Pages media uploads are stored as blobs and resolved locally',async()=>{const api=setup(),p=await create(api),form=new FormData();form.append('file',new Blob([new Uint8Array([1,2,3])],{type:'image/png'}),'photo.png');const a=await api.request(`projects/${p.id}/assets`,{method:'POST',body:form});assert.equal(a.name,'photo.png');assert.match(a.url,/^blob:/);assert.equal((await api.store.get('assets',a.id)).blob.size,3)});
test('Pages rejects active document upload types',async()=>{const api=setup(),p=await create(api),form=new FormData();form.append('file',new Blob(['<svg onload="alert(1)"/>'],{type:'image/svg+xml'}),'bad.svg');await assert.rejects(()=>api.request(`projects/${p.id}/assets`,{method:'POST',body:form}),/Use PNG/)});
async function withMedia(api){const p=await create(api),aid='sample';await api.store.put('assets',{id:aid,project:p.id,name:'test.png',mime:'image/png',blob:new Blob([new Uint8Array([2,4,6,8])],{type:'image/png'}),size:4});p.pages[0].objects[0].src='/api/assets/'+aid;return p}
test('portable packages embed uploaded media and remap on import',async()=>{const a=setup(),p=await withMedia(a),packed=await a.portable(p);assert.equal(packed.assets.length,1);const b=setup(),id=await b.importPortable(packed),restored=(await b.request('projects/'+id)).data;assert.notEqual(id,p.id);const src=restored.pages[0].objects[0].src;assert.notEqual(src,p.pages[0].objects[0].src);const bytes=new Uint8Array(await(await b.store.get('assets',src.slice(12))).blob.arrayBuffer());assert.deepEqual([...bytes],[2,4,6,8])});
test('portable import rejects missing media atomically',async()=>{const a=setup(),p=await withMedia(a),packed=await a.portable(p);packed.assets=[];const b=setup();await assert.rejects(()=>b.importPortable(packed),/missing a referenced/);assert.equal((await b.store.all('projects')).length,0);assert.equal((await b.store.all('assets')).length,0)});
test('portable export rejects missing media instead of incomplete download',async()=>{const api=setup(),p=await create(api);p.pages[0].objects[0].src='/api/assets/not-here';await assert.rejects(()=>api.portable(p),/media file is missing/)});
test('local duplication copies asset ownership',async()=>{const api=setup(),p=await withMedia(api),copy=(await api.create(p)).data;const media=await api.store.get('assets',copy.pages[0].objects[0].src.slice(12));assert.equal(media.project,copy.id);assert.notEqual(copy.pages[0].objects[0].src,p.pages[0].objects[0].src)});
test('Pages sharing explicitly requires hosted service',async()=>{const api=setup(),p=await create(api);await assert.rejects(()=>req(api,`projects/${p.id}/sharing`,'POST',{role:'edit'}),/requires the hosted workspace/)});
test('local imports reject malformed rendering values',async()=>{const api=setup(),p=starter();p.pages[0].objects[0].opacity=100;await assert.rejects(()=>api.create(p),/Invalid numeric/);assert.equal((await api.store.all('projects')).length,0)});
test('portable export rejects a package larger than the import asset-count limit',async()=>{const api=setup(),p=await create(api),base=p.pages[0].objects[0];p.pages[0].objects=Array.from({length:201},(_,i)=>({...clone(base),id:crypto.randomUUID(),src:'/api/assets/media-'+i}));await assert.rejects(()=>api.portable(p),/up to 200 media files/)});
