import test from 'node:test';import assert from 'node:assert/strict';import {Sync} from '../public/studio/sync.js';import {starter,clone} from '../public/studio/model.js';
globalThis.location={search:''};globalThis.document={hidden:false};globalThis.addEventListener=()=>{};globalThis.sessionStorage={getItem:()=>null,setItem:()=>{}};const real=setInterval;globalThis.setInterval=()=>0;
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}};
function session(){const s=new Sync(()=>{},()=>{},()=>{});s.id='A';s.server=starter();s.server.id='A';s.revision=0;s.role='owner';return s}
test('late poll cannot regress an acknowledged revision',async()=>{const s=session(),d=deferred();s.request=()=>d.promise;const poll=s.poll();const after=clone(s.server);after.name='After';s.server=after;s.revision=2;d.resolve({revision:1,data:{...clone(after),name:'Before'},role:'owner',presence:[]});await poll;assert.equal(s.revision,2);assert.equal(s.server.name,'After')});
test('poll is blocked during project open',async()=>{const s=session(),d=deferred();s.request=()=>d.promise;const opening=s.open('B');assert.equal(s.id,null);assert.equal(s.opening,true);await s.poll();d.resolve({data:{...starter(),id:'B'},revision:3,role:'owner'});await opening;assert.equal(s.id,'B');assert.equal(s.server.id,'B')});
test('old project response cannot replace newly opened design',async()=>{const s=session(),pollD=deferred(),openD=deferred();s.request=p=>p==='projects/B'?openD.promise:pollD.promise;const poll=s.poll(),opening=s.open('B');openD.resolve({data:{...starter(),id:'B'},revision:0,role:'owner'});await opening;pollD.resolve({data:{...starter(),id:'A'},revision:9,role:'owner',presence:[]});await poll;assert.equal(s.server.id,'B')});
test('replay pending local edits over remote snapshot',()=>{let shown;const s=session();s.onState=p=>shown=p;s.pending=[{changes:[{kind:'project',key:'name',value:'Local'}]}];s.server.width=1400;s.emit();assert.equal(shown.name,'Local');assert.equal(shown.width,1400)});
test('permanent save errors preserve queue and stop automatic retries',async()=>{const s=session();s.pending=[{id:'bad',changes:[]}];s.request=async()=>{throw Object.assign(Error('Invalid design'),{status:400})};await s.flush();assert.equal(s.pending.length,1);assert.equal(s.rejected,true);let calls=0;s.request=async()=>calls++;await s.flush();assert.equal(calls,0)});
