import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const projects=sqliteTable('projects',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),data:text('data').notNull(),revision:integer('revision').notNull().default(0),updated:integer('updated').notNull(),lastOp:text('last_op'),folder:text('folder').notNull().default(''),starred:integer('starred').notNull().default(0),deleted:integer('deleted').notNull().default(0)},t=>[index('idx_projects_owner_updated').on(t.owner,t.updated)]);
export const members=sqliteTable('members',{project:text('project').notNull(),email:text('email').notNull(),role:text('role').notNull()},t=>[primaryKey({columns:[t.project,t.email]}),index('idx_members_email').on(t.email)]);
export const links=sqliteTable('links',{token:text('token').primaryKey(),project:text('project').notNull(),role:text('role').notNull(),created:integer('created').notNull()},t=>[index('idx_links_project').on(t.project)]);
export const operations=sqliteTable('operations',{id:text('id').primaryKey(),project:text('project').notNull(),actor:text('actor').notNull(),revision:integer('revision').notNull(),changes:text('changes').notNull(),created:integer('created').notNull()},t=>[index('idx_operations_project_revision').on(t.project,t.revision)]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),project:text('project').notNull(),page:text('page').notNull(),author:text('author').notNull(),name:text('name').notNull(),body:text('body').notNull(),created:integer('created').notNull(),resolved:integer('resolved').notNull().default(0)},t=>[index('idx_comments_project').on(t.project)]);
export const presence=sqliteTable('presence',{project:text('project').notNull(),actor:text('actor').notNull(),name:text('name').notNull(),page:text('page'),x:integer('x'),y:integer('y'),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.project,t.actor]}),index('idx_presence_project_updated').on(t.project,t.updated)]);
export const assets=sqliteTable('assets',{id:text('id').primaryKey(),project:text('project').notNull(),owner:text('owner').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),created:integer('created').notNull()},t=>[index('idx_assets_project').on(t.project)]);
export const snapshots=sqliteTable('snapshots',{id:text('id').primaryKey(),project:text('project').notNull(),name:text('name').notNull(),data:text('data').notNull(),created:integer('created').notNull()},t=>[index('idx_snapshots_project').on(t.project)]);
